// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tournament.Domain.DataBase.DBContext;

#nullable disable

namespace Tournament.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250517054814_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.LeaderboardEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BestMultiplier")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPoints")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalStake")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalWin")
                        .HasColumnType("numeric");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TournamentPlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("TournamentPlayerId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EntityRefId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EventRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SourceValue")
                        .HasColumnType("numeric");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WinAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentEvents");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EligibilityPassed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId");

                    b.ToTable("TournamentParticipants");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentParticipationRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MinBetAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("MinEvents")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinOdd")
                        .HasColumnType("numeric");

                    b.Property<int?>("MinSpinsCount")
                        .HasColumnType("integer");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("TournamentParticipationRules");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<long>("EventId1")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("WinAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EventId1");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPoints");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentPrize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("PrizeAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("PrizeType")
                        .HasColumnType("integer");

                    b.Property<int>("RankFrom")
                        .HasColumnType("integer");

                    b.Property<int>("RankTo")
                        .HasColumnType("integer");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPrizes");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.LeaderboardEntry", b =>
                {
                    b.HasOne("Tournament.Domain.DataBase.Entity.TournamentEntity", "Tournament")
                        .WithMany("LeaderboardEntries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tournament.Domain.DataBase.Entity.TournamentParticipant", "TournamentPlayer")
                        .WithMany()
                        .HasForeignKey("TournamentPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("TournamentPlayer");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentEvent", b =>
                {
                    b.HasOne("Tournament.Domain.DataBase.Entity.TournamentEntity", "Tournament")
                        .WithMany("Events")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentParticipant", b =>
                {
                    b.HasOne("Tournament.Domain.DataBase.Entity.TournamentEntity", "Tournament")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tournament.Domain.DataBase.Entity.User", "User")
                        .WithMany("TournamentParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentParticipationRule", b =>
                {
                    b.HasOne("Tournament.Domain.DataBase.Entity.TournamentEntity", "Tournament")
                        .WithOne("ParticipationRules")
                        .HasForeignKey("Tournament.Domain.DataBase.Entity.TournamentParticipationRule", "TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentPoint", b =>
                {
                    b.HasOne("Tournament.Domain.DataBase.Entity.TournamentEvent", "Event")
                        .WithMany("Points")
                        .HasForeignKey("EventId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tournament.Domain.DataBase.Entity.TournamentEntity", "Tournament")
                        .WithMany("Points")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentPrize", b =>
                {
                    b.HasOne("Tournament.Domain.DataBase.Entity.TournamentEntity", "Tournament")
                        .WithMany("Prizes")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("LeaderboardEntries");

                    b.Navigation("Participants");

                    b.Navigation("ParticipationRules")
                        .IsRequired();

                    b.Navigation("Points");

                    b.Navigation("Prizes");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.TournamentEvent", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("Tournament.Domain.DataBase.Entity.User", b =>
                {
                    b.Navigation("TournamentParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
